### ISSUE TITLE
History.js Adapter has already been loaded...

### ISSUE THREAD

**Issue by richtabor** [AutoLoadNextPost/Auto-Load-Next-Post#104]
Hey there! I'm working on adding support for ALNP in my theme Tabor. Everything works flawlessly on the front-end, but when it comes to the Customizer, I'm getting a "Error: History.js Adapter has already been loaded..." console error, which bonks the Customizer view and renders it a mess. 

Is this something you've seen before? Cheers!

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Auto Load Next Post on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue.

## Steps to reproduce the issue

1. Install the plugin and configure it.
2. Open the Customizer and navigate to a singular post view.
3. Scroll. Error will appear.

## Expected/actual behavior

Either the plugin should not load within the Customizer, or it should function properly.

## Isolating the problem

- [x] This bug happens with only Auto Load Next Post plugin active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by seb86** [comment]
Hi @richtabor

Thank you for posting this issue. I have not had this error before or had issues accessing the customizer with ALNP active but I am aware that ALNP is currently unable to determine if the site is being viewed normally or in the customize which causes a strange experience when viewing posts as all links are replaced.

I have not yet had the time to provide a solution but you are welcome to come up with one and push a PR. Please follow the [contributing guidelines](https://github.com/AutoLoadNextPost/Auto-Load-Next-Post/blob/master/CONTRIBUTING.md).

If you have any questions please let me know.

Thank you.

P.S. Love your themes.

**Comment by richtabor** [comment]
Thanks @seb86,

What do you think about essentially stopping the plugin from functioning completely within the Customizer?

**Comment by seb86** [comment]
This would prevent what I had in mind for issue #30. Would it be possible to just prevent jquery.history.js from loading if viewing the customizer?

If history.js is already loaded then I see no harm in preventing it from loading again. It's possible the customizer uses its own history.js that I am not aware of which is now causing this new issue.

See what happens if you put the condition around [#L240](https://github.com/AutoLoadNextPost/Auto-Load-Next-Post/blob/master/auto-load-next-post.php#L240).

**Comment by richtabor** [comment]
I tried that as well. The issue remains unless both [#L240 and #L241](https://github.com/AutoLoadNextPost/Auto-Load-Next-Post/blob/master/auto-load-next-post.php#L240-L241) are not loaded within the Customizer.

I'm a huge fan of plugin options within the Customizer. Though if this issue persists, then the options can't be added to the Customizer anyhow, yea? I double-checked Twenty Fourteen, of the compatible themes listed, and the Customizer throws errors/duplicated content there as well. 

The ALNP front-end is flawless and works wonderfully. That's awesome! It performs as expected with my theme, Tabor, though I just can't recommend ALNP with the current Customizer issues. My themes rely heavily on the Theme Customization API. 

Have any other ideas?

**Comment by seb86** [comment]
If I wanted to support the customizer at a later time could I make the JavaScript load on request or only for a certain section of the customizer?

**Comment by seb86** [comment]
Can you provide a screenshot or a screen recording of the issue because I am in the customizer with Twenty Fourteen and although I see the error logged in the console, the customizer is still working?

Also...

1. Do you have other plugins active?
2. Could this be a jQuery version issue?

**Comment by seb86** [comment]
I think what would be best until I can work on the customizer more would be to add the condition to [all three assets](https://github.com/AutoLoadNextPost/Auto-Load-Next-Post/blob/master/auto-load-next-post.php#L239-L241). 

I don't see how I could get to use history.js in the customizer anyway but would still want to allow the user to preview the plugin in action as they set it up. So I will leave issue #30 for now until I am able to work it all out.

**Comment by richtabor** [comment]
Here's a gif using the Twenty Fourteen theme, viewing it from a singular post view. No other plugins are installed.

![screenflick movie 67](https://user-images.githubusercontent.com/1813435/34630206-2d243942-f239-11e7-8721-ba2a1ae55759.gif)

**Comment by seb86** [comment]
I get the same results. I thought something else was causing the customizer control panel to not work for you but yeah this is what happens currently.

The reason why this is happening is that the customizer is adding parameters to all the links and Auto Load Next Post does not yet understand how to load the next post as designed.

Auto Load Next Post reads a new rewrite rule in order to load the next post content using the template provided so at the moment what you see is the whole single post loading which will be different based on the theme you are viewing.

This is what ALNP reads when loading the next post. **http://example.com/hello-world/** and then ALNP adds **/partial/** at the end of the permalink in order to load the post via the custom template.

But in the customizer, the permalink is not clean and has parameters already added which stops the rewrite rule from working and simply applies the page at the end of the content.

I am working on a new branch to focus on the [customizer](https://github.com/AutoLoadNextPost/Auto-Load-Next-Post/tree/customizer). The only option that I see is that I have to add conditions within the JavaScript to look for the parameters the customizer adds and remove them before ALNP tries to load the next post.

I do have a [JS trigger](https://github.com/AutoLoadNextPost/Auto-Load-Next-Post/blob/master/assets/js/frontend/auto-load-next-post.dev.js#L153) I can use which I have yet to try so I hope it works. This would allow me to keep the functions clean.

When is your next theme update?

**Comment by richtabor** [comment]
Ah, I see. An interesting dilemma indeed. The update will go out this afternoon, though I will probably revert the ALNP support branch until it's good to go within the Customizer.

**Comment by seb86** [comment]
That's fine. I hope to have an update soon.

**Comment by seb86** [comment]
@richtabor I think I know what is causing the console error log for the History script ([#L166](https://github.com/AutoLoadNextPost/Auto-Load-Next-Post/blob/master/assets/js/frontend/auto-load-next-post.dev.js#L166)).

Luckily the rest of the Javascript is actually doing its job so I just need to add a parameter to the JavaScript to identify ([#L244](https://github.com/AutoLoadNextPost/Auto-Load-Next-Post/blob/master/auto-load-next-post.php#L244)) if the site is being viewed within the Customizer.

**Comment by richtabor** [comment]
Oh cool! Around what time-frame are you expecting for the [1.4.X](https://github.com/AutoLoadNextPost/Auto-Load-Next-Post/milestone/8) milestone?

**Comment by seb86** [comment]
@richtabor I am aiming for sometime near the end of January. Still a lot on my plate at the moment. Organizing and all.
